# Site settings
title: Kayhan
description: Data Scientist
#baseurl:  # the subpath of your site, e.g. /blog
url: "kayhanliao.com" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: KAYHAN Eryılmaz
user_description:
user_title: Data Scientist
email: kayhankubi@gmail.com

exclude: ['package.json', 'src' , 'node_modules']
